# Stage 1: isolate the packaged artifact produced by Maven before the image build.
FROM node:20-alpine AS artifact

WORKDIR /artifact

# The shaded JAR is generated by `mvn clean package` before `docker build`.
COPY target/books-crawler-java-1.0.0.jar /artifact/books-crawler-java.jar

# Stage 2: run the application on a lightweight non-root image.
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openjdk21-jre-headless

# Create a dedicated user to avoid running the container as root.
RUN addgroup -S crawler && adduser -S crawler -G crawler

# Copy the packaged artifact from the artifact stage.
COPY --from=artifact /artifact/books-crawler-java.jar /app/books-crawler-java.jar

# Create the output directory and grant ownership to the non-root user.
RUN mkdir -p /app/output && chown -R crawler:crawler /app

USER crawler

# The HTTP port is used by the optional server mode for health checks and on-demand runs.
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/books-crawler-java.jar"]
CMD ["--server", "--port", "8080", "--output-dir", "/app/output"]
